[project]
name = "exonwebui-static"
version = "1.2.dev"
description = "Collected 3rd party UI static contents for web applications."
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
authors = [
    { name = "exonlabs", email = "info@exonlabs.net" }
]
keywords = [
    "development",
    "utilities",
    "tools",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.9"
dependencies = [
]

[project.optional-dependencies]
dev = [
]
docs = [
]

[project.urls]
Homepage = "https://github.com/exonlabs/py-exonwebui-static"
Repository = "https://github.com/exonlabs/py-exonwebui-static"

[build-system]
requires = ["setuptools>=82.0"]
build-backend = "setuptools.build_meta"
